name: Update citations & build data

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"  # 03:30 JST daily (GitHub cron is UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      - name: Build data
        env:
          OPENALEX_MAILTO: ${{ secrets.OPENALEX_MAILTO }}
          TARGET_DOI: 10.1145/3183713.3196909
        run: |
          python scripts/fetch_and_build.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update data: $(date -u +"%Y-%m-%dT%H:%MZ")" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 